#!/usr/bin/env bash

if [ ${#@} -ne 0 ] && [ "${@#"--test"}" = "" ]; then
  targets="testreactapp"
else
  targets="redis dynamodb express-server next-react"
fi

printf "\nTargets: [$targets]\n\n"


if [ "$1" == "b" ] || [ "$1" == "B" ] || [ "$1" == "build" ] || [ "$1" == "BUILD" ]; then
  docker-compose build $targets
fi 

docker-compose up $targets

